services:
  webapi:
    image: ghcr.io/byndum/ahrem:latest

     
    depends_on:
      - mariadb
    ports:
      - "5051:5051"

  mariadb:
    image: mariadb:11.2
    environment:
      MariaDBRootPassword: $${{ secrets.DATABASE_ROOT_PASSWORD }}
      MariaDBName: $${{ vars.DATABASE_NAME }}
      MariaDBUser: $${{ vars.DATABASE_USER }}
      MariaDBPassword: $${{ secrets.DATABASE_PASSWORD }}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    volumes:
      - ./db/migrations:/flyway/sql
    command: [ "migrate" ]
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/$${{ vars.DATABASE_NAME }}
      FLYWAY_USER: $${{ vars.DATABASE_USER }}
      FLYWAY_PASSWORD: $${{ secrets.DATABASE_PASSWORD }}
    restart: on-failure

volumes:
  mariadb_data:
