services:
  mariadb:
    image: mariadb:11.2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085

  webapi:
    image: ghcr.io/byndum/ahrem:latest
    depends_on:
      - mariadb
    ports:
      - "5051:5051"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    volumes:
      - ./db/migrations:/flyway/sql
    command: [ "migrate" ]
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/$${{ vars.DATABASE_NAME }}
      FLYWAY_USER: $${{ vars.DATABASE_USER }}
      FLYWAY_PASSWORD: $${{ secrets.DATABASE_PASSWORD }}
    restart: on-failure

volumes:
  mariadb_data:
  featurehub-h2-data:
  rps_seq_data:
