name: E2E Tests

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci

      - name: Build and run projects
        run: |
          dotnet build API/API.csproj
          dotnet build Frontend/Frontend.csproj
          dotnet run --project API/API.csproj &
          dotnet run --project Frontend/Frontend.csproj &
          sleep 10  # Wait for both apps to start

      - name: Run TestCafe (Headless)
        run: npx testcafe chrome:headless e2e/device.test.js
